### PR TITLE
Add create_* methods to kafnafparser and made python2+3 compatible

### PR DESCRIPTION
**Pull request by vanatteveldt**
I added the create_methods to KafNafParser as discussed over the mail. 

I first had to change all tabs to spaces as per PEP8, but also because my editor really dislikes tabs, so it's best to look at the diff of the second commit (https://github.com/cltl/KafNafParserPy/commit/bcc44d4f184646e33cf15aee5127c17a4c8df6c0)

 Some possible points of discussion:
- I didn't create automatic offset and sentence handling, as that would require keeping state
- I did add automatic ids, which will be {t,w}XX, where XX is the number of known terms/tokens plus one, as taken from the idx dict in the layer. This also required adding new terms to the idx dict, but I think that is probably a good idea anyway? I also added a check against duplicate ids in the add_ method.
- I copied the str(.) methods from the treetagger, but shouldn't we use unicode(.) instead? 

I also made a first unit test which you can run with `nosetests` in the main folder. (third commit)

Finally, (based on @martijnbastiaan's https://github.com/cltl/KafNafParserPy/pull/4) I made it compatible with both python2 and python3, and changed the folder structure to match the recommended python-packaging layout.

As an example of usage, I re-created the frog_naf.py with the new method, which I think strikes the right balance of sticking close to the "metal" (you still need to create separate term and token objects and handle offset/sentence counting yourself) while not needing too much boilerplate code. https://gist.github.com/vanatteveldt/df15c4b68584dd7465d3

### CODE REVIEW

**Comment by vanatteveldt** [comment]
Perfect, thanks!

**Comment by rubenIzquierdo** [comment]
About your points of discussion:
- I don't think it's a problem creating the offsets and sentences like that, althought using a coupl of internal attributes in the main object to keep the state wouldn't hurt that much
- About the internal dictionaries and indexes... we can either update the index while creating tokens/terms or include a checking in the function to access to a token/term, so in case the indexes are not created, we call to the function to create them. I kind of prefer the first option

**Comment by vanatteveldt** [comment]
About the indices: so essentially you would be seeing _idx as a "cache", rather than as the real data (which resides in de lxml structure). 

In that case, it would still be good to add to the idx on adding something to a layer (why not update the cache when we have the data anyway), but the "already exists" check would need to use the underlying get_node function and error when a node was found that's not the node that is being added, right?

**Comment by rubenIzquierdo** [comment]
Indeed, I always used the_idx as a cache to access quickly to a certain node for a given id without having to iterate over the whole XML. Updating the idx when adding new information to the file seems a good option

**Pull request merged**
